[package]
name = "backpacktf-api"
version = "0.1.0"
edition = "2021"
description = "Interface for backpack.tf API endpoints."
authors = ["Julia"]
homepage = "https://github.com/juliarose/backpacktf-api"
repository = "https://github.com/juliarose/backpacktf-api"
license = "MIT"
keywords = ["tf2", "steam"]
readme = "README.md"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
reqwest = { version = "^0.11.7", features = ["json", "cookies"] }
reqwest-retry = "^0.1.3"
reqwest-middleware = "^0.1.2"
url = "^2.2.2"
chrono = { version = "^0.4", features = ["serde"] }
anyhow = "^1.0"
num_enum = "^0.5.5"
strum = { version = "^0.23", features = ["derive"] }
strum_macros = "^0.23"
thiserror = "^1.0.30"
steamid-ng = "1.0.0"
tf2-enum = "0.1.0"
tf2-price = { version = "0.2.0" }

[dev-dependencies]
assert-json-diff = "^2.0.1"
